[tools]
node = "22.16.0"

[tasks.audit]
run = "pnpm run audit"

[tasks.build]
run = "pnpm run build"

[tasks.lint]
run = "pnpm run lint"

[tasks.test]
run = "pnpm test"

[tasks.type-check]
run = "pnpm run type-check"